-- Site-wide text and image overrides for Nutristika

create table if not exists public.site_content_overrides (
  id bigint generated by default as identity primary key,
  key text not null,
  value text not null,
  content_type text not null check (content_type in ('text', 'image')),
  language text not null default 'all' check (language in ('all', 'en', 'de')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_content_overrides_unique unique (key, content_type, language)
);

create or replace function public.set_site_content_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_site_content_updated_at on public.site_content_overrides;
create trigger trg_site_content_updated_at
before update on public.site_content_overrides
for each row
execute function public.set_site_content_updated_at();

alter table public.site_content_overrides enable row level security;

create or replace function public.has_admin_claim()
returns boolean
language sql
stable
as $$
  select
    coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') = 'admin'
    or coalesce((auth.jwt() -> 'app_metadata' -> 'roles') ? 'admin', false);
$$;

-- Allow anyone to read override content (public site fetch).
drop policy if exists "Public read site_content_overrides" on public.site_content_overrides;
create policy "Public read site_content_overrides"
on public.site_content_overrides
for select
using (true);

-- Allow writes only to authenticated users with app_metadata.role = 'admin'.
drop policy if exists "Admin write site_content_overrides" on public.site_content_overrides;
create policy "Admin write site_content_overrides"
on public.site_content_overrides
for all
to authenticated
using (public.has_admin_claim())
with check (public.has_admin_claim());
